// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable, constant_identifier_names

library my_game.sample;

import 'dart:typed_data' show Uint8List;
import 'package:flat_buffers/flat_buffers.dart' as fb;


enum Color {
  Red(0),
  Green(1),
  Blue(2);

  final int value;
  const Color(this.value);

  factory Color.fromValue(int value) {
    switch (value) {
      case 0: return Color.Red;
      case 1: return Color.Green;
      case 2: return Color.Blue;
      default: throw StateError('Invalid value $value for bit flag enum');
    }
  }

  static Color? _createOrNull(int? value) =>
      value == null ? null : Color.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 2;
  static const fb.Reader<Color> reader = _ColorReader();
}

class _ColorReader extends fb.Reader<Color> {
  const _ColorReader();

  @override
  int get size => 1;

  @override
  Color read(fb.BufferContext bc, int offset) =>
      Color.fromValue(const fb.Int8Reader().read(bc, offset));
}

enum EquipmentTypeId {
  NONE(0),
  Weapon(1);

  final int value;
  const EquipmentTypeId(this.value);

  factory EquipmentTypeId.fromValue(int value) {
    switch (value) {
      case 0: return EquipmentTypeId.NONE;
      case 1: return EquipmentTypeId.Weapon;
      default: throw StateError('Invalid value $value for bit flag enum');
    }
  }

  static EquipmentTypeId? _createOrNull(int? value) =>
      value == null ? null : EquipmentTypeId.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 1;
  static const fb.Reader<EquipmentTypeId> reader = _EquipmentTypeIdReader();
}

class _EquipmentTypeIdReader extends fb.Reader<EquipmentTypeId> {
  const _EquipmentTypeIdReader();

  @override
  int get size => 1;

  @override
  EquipmentTypeId read(fb.BufferContext bc, int offset) =>
      EquipmentTypeId.fromValue(const fb.Uint8Reader().read(bc, offset));
}

class Vec3 {
  Vec3._(this._bc, this._bcOffset);

  static const fb.Reader<Vec3> reader = _Vec3Reader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  double get x => const fb.Float32Reader().read(_bc, _bcOffset + 0);
  double get y => const fb.Float32Reader().read(_bc, _bcOffset + 4);
  double get z => const fb.Float32Reader().read(_bc, _bcOffset + 8);

  @override
  String toString() {
    return 'Vec3{x: ${x}, y: ${y}, z: ${z}}';
  }

  Vec3T unpack() => Vec3T(
      x: x,
      y: y,
      z: z);

  static int pack(fb.Builder fbBuilder, Vec3T? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class Vec3T implements fb.Packable {
  double x;
  double y;
  double z;

  Vec3T({
      required this.x,
      required this.y,
      required this.z});

  @override
  int pack(fb.Builder fbBuilder) {
    fbBuilder.putFloat32(z);
    fbBuilder.putFloat32(y);
    fbBuilder.putFloat32(x);
    return fbBuilder.offset;
  }

  @override
  String toString() {
    return 'Vec3T{x: ${x}, y: ${y}, z: ${z}}';
  }
}

class _Vec3Reader extends fb.StructReader<Vec3> {
  const _Vec3Reader();

  @override
  int get size => 12;

  @override
  Vec3 createObject(fb.BufferContext bc, int offset) =>
    Vec3._(bc, offset);
}

class Vec3Builder {
  Vec3Builder(this.fbBuilder);

  final fb.Builder fbBuilder;

  int finish(double x, double y, double z) {
    fbBuilder.putFloat32(z);
    fbBuilder.putFloat32(y);
    fbBuilder.putFloat32(x);
    return fbBuilder.offset;
  }

}

class Vec3ObjectBuilder extends fb.ObjectBuilder {
  double x;
  double y;
  double z;

  Vec3ObjectBuilder({
    required this.x,
    required this.y,
    required this.z,
  });

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.putFloat32(z);
    fbBuilder.putFloat32(y);
    fbBuilder.putFloat32(x);
    return fbBuilder.offset;
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Monster {
  Monster._(this._bc, this._bcOffset);
  factory Monster(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Monster> reader = _MonsterReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  Vec3? get pos => Vec3.reader.vTableGetNullable(_bc, _bcOffset, 4);
  int get mana => const fb.Int16Reader().vTableGet(_bc, _bcOffset, 6, 150);
  int get hp => const fb.Int16Reader().vTableGet(_bc, _bcOffset, 8, 100);
  String? get name => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 10);
  List<int>? get inventory => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 14);
  Color get color => Color.fromValue(const fb.Int8Reader().vTableGet(_bc, _bcOffset, 16, 2));
  List<Weapon>? get weapons => const fb.ListReader<Weapon>(Weapon.reader).vTableGetNullable(_bc, _bcOffset, 18);
  EquipmentTypeId? get equippedType => EquipmentTypeId._createOrNull(const fb.Uint8Reader().vTableGetNullable(_bc, _bcOffset, 20));
  Object? get equipped {
    switch (equippedType?.value) {
      case 1: return Weapon.reader.vTableGetNullable(_bc, _bcOffset, 22);
      default: return null;
    }
  }
  List<Vec3>? get path => const fb.ListReader<Vec3>(Vec3.reader).vTableGetNullable(_bc, _bcOffset, 24);

  @override
  String toString() {
    return 'Monster{pos: ${pos}, mana: ${mana}, hp: ${hp}, name: ${name}, inventory: ${inventory}, color: ${color}, weapons: ${weapons}, equippedType: ${equippedType}, equipped: ${equipped}, path: ${path}}';
  }

  MonsterT unpack() => MonsterT(
      pos: pos?.unpack(),
      mana: mana,
      hp: hp,
      name: name,
      inventory: const fb.Uint8ListReader(lazy: false).vTableGetNullable(_bc, _bcOffset, 14),
      color: color,
      weapons: weapons?.map((e) => e.unpack()).toList(),
      equippedType: equippedType,
      equipped: equipped,
      path: path?.map((e) => e.unpack()).toList());

  static int pack(fb.Builder fbBuilder, MonsterT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class MonsterT implements fb.Packable {
  Vec3T? pos;
  int mana;
  int hp;
  String? name;
  List<int>? inventory;
  Color color;
  List<WeaponT>? weapons;
  EquipmentTypeId? equippedType;
  Object? equipped;
  List<Vec3T>? path;

  MonsterT({
      this.pos,
      this.mana = 150,
      this.hp = 100,
      this.name,
      this.inventory,
      this.color = Color.Blue,
      this.weapons,
      this.equippedType,
      this.equipped,
      this.path});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? nameOffset = name == null ? null
        : fbBuilder.writeString(name!);
    final int? inventoryOffset = inventory == null ? null
        : fbBuilder.writeListUint8(inventory!);
    final int? weaponsOffset = weapons == null ? null
        : fbBuilder.writeList(weapons!.map((b) => b.pack(fbBuilder)).toList());
    var equippedOffset = 0;
    if (equipped != null && equippedType != null) {
      if (equippedType == EquipmentTypeId.Weapon) {
        if (equipped is! WeaponT) {
          throw ArgumentError('Invalid union type');
        }
        equippedOffset = (equipped as WeaponT).pack(fbBuilder);
      }
    }
    int? pathOffset;
    if (path != null) {
      for (var e in path!) { e.pack(fbBuilder); }
      pathOffset = fbBuilder.endStructVector(path!.length);
    }
    fbBuilder.startTable(11);
    if (pos != null) {
      fbBuilder.addStruct(0, pos!.pack(fbBuilder));
    }
    fbBuilder.addInt16(1, mana);
    fbBuilder.addInt16(2, hp);
    fbBuilder.addOffset(3, nameOffset);
    fbBuilder.addOffset(5, inventoryOffset);
    fbBuilder.addInt8(6, color.value);
    fbBuilder.addOffset(7, weaponsOffset);
    fbBuilder.addUint8(8, equippedType?.value ?? 0);
    fbBuilder.addOffset(9, equippedOffset);
    fbBuilder.addOffset(10, pathOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'MonsterT{pos: ${pos}, mana: ${mana}, hp: ${hp}, name: ${name}, inventory: ${inventory}, color: ${color}, weapons: ${weapons}, equippedType: ${equippedType}, equipped: ${equipped}, path: ${path}}';
  }
}

class _MonsterReader extends fb.TableReader<Monster> {
  const _MonsterReader();

  @override
  Monster createObject(fb.BufferContext bc, int offset) =>
    Monster._(bc, offset);
}

class MonsterBuilder {
  MonsterBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(11);
  }

  int addPos(int offset) {
    fbBuilder.addStruct(0, offset);
    return fbBuilder.offset;
  }
  int addMana(int? mana) {
    fbBuilder.addInt16(1, mana);
    return fbBuilder.offset;
  }
  int addHp(int? hp) {
    fbBuilder.addInt16(2, hp);
    return fbBuilder.offset;
  }
  int addNameOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }
  int addInventoryOffset(int? offset) {
    fbBuilder.addOffset(5, offset);
    return fbBuilder.offset;
  }
  int addColor(Color? color) {
    fbBuilder.addInt8(6, color?.value);
    return fbBuilder.offset;
  }
  int addWeaponsOffset(int? offset) {
    fbBuilder.addOffset(7, offset);
    return fbBuilder.offset;
  }
  int addEquippedType(EquipmentTypeId? equippedType) {
    fbBuilder.addUint8(8, equippedType?.value);
    return fbBuilder.offset;
  }
  int addEquippedOffset(int? offset) {
    fbBuilder.addOffset(9, offset);
    return fbBuilder.offset;
  }
  int addPathOffset(int? offset) {
    fbBuilder.addOffset(10, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class MonsterObjectBuilder extends fb.ObjectBuilder {
  Vec3ObjectBuilder? pos;
  int? mana;
  int? hp;
  String? name;
  List<int>? inventory;
  Color? color;
  List<WeaponObjectBuilder>? weapons;
  EquipmentTypeId? equippedType;
  Object? equipped;
  List<Vec3ObjectBuilder>? path;

  MonsterObjectBuilder({
    this.pos,
    this.mana,
    this.hp,
    this.name,
    this.inventory,
    this.color,
    this.weapons,
    this.equippedType,
    this.equipped,
    this.path,
  })
      : assert((equipped == null) || (equippedType != null && equippedType != EquipmentTypeId.NONE));

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? nameOffset = name == null ? null
        : fbBuilder.writeString(name!);
    final int? inventoryOffset = inventory == null ? null
        : fbBuilder.writeListUint8(inventory!);
    final int? weaponsOffset = weapons == null ? null
        : fbBuilder.writeList(weapons!.map((b) => b.finish(fbBuilder)).toList());
    var equippedOffset = 0;
    if (equipped != null && equippedType != null) {
      if (equippedType == EquipmentTypeId.Weapon) {
        if (equipped is! WeaponObjectBuilder) {
          throw ArgumentError('Invalid union type');
        }
        equippedOffset = (equipped as WeaponObjectBuilder).finish(fbBuilder);
      }
    }
    final int? pathOffset = path == null ? null
        : fbBuilder.writeListOfStructs(path!);
    fbBuilder.startTable(11);
    if (pos != null) {
      fbBuilder.addStruct(0, pos!.finish(fbBuilder));
    }
    fbBuilder.addInt16(1, mana);
    fbBuilder.addInt16(2, hp);
    fbBuilder.addOffset(3, nameOffset);
    fbBuilder.addOffset(5, inventoryOffset);
    fbBuilder.addInt8(6, color?.value);
    fbBuilder.addOffset(7, weaponsOffset);
    fbBuilder.addUint8(8, equippedType?.value ?? 0);
    fbBuilder.addOffset(9, equippedOffset);
    fbBuilder.addOffset(10, pathOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Weapon {
  Weapon._(this._bc, this._bcOffset);
  factory Weapon(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Weapon> reader = _WeaponReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get name => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  int get damage => const fb.Int16Reader().vTableGet(_bc, _bcOffset, 6, 0);

  @override
  String toString() {
    return 'Weapon{name: ${name}, damage: ${damage}}';
  }

  WeaponT unpack() => WeaponT(
      name: name,
      damage: damage);

  static int pack(fb.Builder fbBuilder, WeaponT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class WeaponT implements fb.Packable {
  String? name;
  int damage;

  WeaponT({
      this.name,
      this.damage = 0});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? nameOffset = name == null ? null
        : fbBuilder.writeString(name!);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, nameOffset);
    fbBuilder.addInt16(1, damage);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'WeaponT{name: ${name}, damage: ${damage}}';
  }
}

class _WeaponReader extends fb.TableReader<Weapon> {
  const _WeaponReader();

  @override
  Weapon createObject(fb.BufferContext bc, int offset) =>
    Weapon._(bc, offset);
}

class WeaponBuilder {
  WeaponBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addNameOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addDamage(int? damage) {
    fbBuilder.addInt16(1, damage);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class WeaponObjectBuilder extends fb.ObjectBuilder {
  String? name;
  int? damage;

  WeaponObjectBuilder({
    this.name,
    this.damage,
  });

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? nameOffset = name == null ? null
        : fbBuilder.writeString(name!);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, nameOffset);
    fbBuilder.addInt16(1, damage);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}